### ISSUE TITLE
APK files in releases show wrong version number

### ISSUE THREAD

**Issue by IzzySoft** [openhab/org.openhab.ui.habmin#185]
Regardless of the version pointed out by the file name, package info always shows:

```
package: name='com.cd_jackson.habmin' versionCode='10000' versionName='1.0.0'
```

So by that, different versions cannot be told apart – which of course confuses package managers etc. (also see [here](https://github.com/cdjackson/HABmin2/issues/151#issuecomment-226990498)).
##

**Comment by cdjackson** [comment]
Build updated

**Comment by IzzySoft** [comment]
@cdjackson Looks like they're gone completely now? I cannot see a single `.apk` file in `releases/` since. Could you please check?

**Comment by IzzySoft** [comment]
Still not there. Just kindly asking if they'll return?

**Comment by IzzySoft** [comment]
OK, it's more than a year now. The last APK that ever had been attached was v1.0.0. According to the tags, the latest version is v2.1.0. As I never got a reply, I assume this is considered "won't fix". Giving up on it then and removing the app from my repo.

Be welcome to ping me if you decide otherwise, so I can consider adding it back.
