### ISSUE TITLE
Linear WA105DBZ version problem in Database

### ISSUE THREAD

**Issue by robschoon** [openhab/org.openhab.ui.habmin#199]
I have a Linear WA105DBZ-1 Siren & Strobe. It appears to be identical to the WA105DBZ which is in the database, but the type and id are different.
Mine is:

  <manufacturer>0x14f</manufacturer>
  <deviceId>0x903</deviceId>
  <deviceType>0x2009</deviceType>

The database has:

```
  <property name="manufacturerId">014F</property>
  <property name="manufacturerRef">2005:0503</property>
```

so when installing I get "unknown device".

I tried to upload the openhab2 xml, but that gives me a red exclamation mark and 

`thingid` contains invalid characters.
Device supports configuration, but no parameters are defined.

I probably would be well off with (a duplicate of) the existing entry, but then with the correct Ref 2009:0903. I need the same property parameters as well.
My instruction leaflet is identical to the one on file. Any suggestions for the best way forward?
[node57.txt](https://github.com/cdjackson/HABmin2/files/392042/node57.txt)
##

**Comment by cdjackson** [comment]
I see you updated the database for the -1 version - is there any difference with the version that doesn’t have the -1? It looks not - I’ve actually approved the -1 version, but since I suspect they are the same, we’re better off to simply add new references to the current version...

**Comment by robschoon** [comment]
You're right, apart from the id/type  number they seem identical, so better to just delete my (incomplete) entry and add the new reference to the existing one. Not sure how to do that - many thanks for taking care of that, hope it's not too inconvenient.

**Comment by cdjackson** [comment]
No problem - thanks.

**Comment by davispw** [comment]
What still needs to be done on this issue?  I've got a siren model ZM1601US, which reports

```
<Manufacturer id="14f" name="Linear">
	<Product type="2005" id="503" name="Unknown: type=2005, id=0503" />
</Manufacturer>
```

**Comment by cdjackson** [comment]
This is not related to HABmin so closing this. I'd suggest to discuss on the openHAB forum.
