### ISSUE TITLE
sitemaps are not populated

### ISSUE THREAD

**Issue by sutyagin** [openhab/org.openhab.ui.habmin#204]
hi
i have started new setup with OP2 and the issue is that sitemaps are not populated in habmin.
I have 2 sitemaps demo and my new one home.
I can see them from manual oh server:8080/classicui/app OK
the items and things are populated ok in habmin.
I have checked and permissions seems to be ok and set to openhab user

which folder habmin shall take sitemaps from ?

**Comment by cdjackson** [comment]
They are probably read from config/sitemaps folder. If your system uses a different folder, then this won’t work.

**Comment by sutyagin** [comment]
ok, but it reads items and things ok....
i'm using the following folders:
/etc/openhab2/sitemaps
/usr/share/openhab2/conf/sitemaps

**Comment by cdjackson** [comment]
Ok - this is the OH1 version of HABmin that you have raised this issue on, so my answer was related to OH1.

OH2 is a different version completely and it only reads sitemaps through the OH api. However sitemaps are not well supported in HABmin at the moment as there is no official sitemap concept in ESH.

Further question on HABmin2 should be raised on the [HABmin issue list](https://github.com/openhab/org.openhab.ui.habmin).

**Comment by sutyagin** [comment]
sorry but how can i raise it with habmin2? 
can you please advise how op2 should be configured for habmin2 to pickup sitemaps?

**Comment by cdjackson** [comment]
HABmin uses the standard OH2 API for sitemaps, so if it works with other UIs, then it should work with HABmin.

If you have a problem with sitemaps in general, then I would discuss it on the community forum. The HABmin2 repo is here (https://github.com/openhab/org.openhab.ui.habmin).

**Comment by sutyagin** [comment]
ok, thanks.
the problem is that sitemaps working on with other UIs but not with Habmin.
