### ISSUE TITLE
Saving decimal type config parameter not being persisted

### ISSUE THREAD

**Issue by mhilbush** [openhab/org.openhab.ui.habmin#238]
If I have a thing config parameter defined like this, when I try to save a new value using HABmin, the change is not persisted.  When I do the same function using Paper UI, the change is persisted.

The specific case was changing the default (8.0) to 20.0.

```
        <config-description uri="thing-type:sunsetwx:config">
            <parameter name="radius" type="decimal" required="true" min="0.0" max="1667.0">
                <label>Radius</label>
                <description>Enter the radius in kilometers</description>
                <default>8.0</default>
            </parameter>
        </config-description>
```
##

**Comment by cdjackson** [comment]
I've made a change that I hope will fix this - I'll kick off a build soon - I just want to look at another issue first...

**Comment by mhilbush** [comment]
That worked.

**Comment by cdjackson** [comment]
Thanks.
