### ISSUE TITLE
Add Last update for battery device as channel

### ISSUE THREAD

**Issue by stadlersamuel** [openhab/org.openhab.ui.habmin#240]
Hi cdjackson,
At first thanks for yours great work...
Just small idea, to add for battery working zwave devices last update as channel to have possibility to work with that.
Thanks
##

**Comment by cdjackson** [comment]
Hi,
Sorry - I’m not sure I understand. To be clear - you want a battery indicator, or a "last received” time to be displayed?

Cheers
Chris

**Comment by stadlersamuel** [comment]
Hi,
All battery devices have its own last communication (Habmin ->Thinks -> Node -> Attributes -> Last Wakeup Time) And to have it as channel to link item.

**Comment by cdjackson** [comment]
This isn't related to HABmin - it's a zwave issue.
