### ISSUE TITLE
habmin will not save a polling period for a device longer than 7200s

### ISSUE THREAD

**Issue by xsnrg** [openhab/org.openhab.ui.habmin#242]
![pollingperiod](https://cloud.githubusercontent.com/assets/1186921/19410692/4cfbd40a-92b8-11e6-9a15-01759f58fb7e.png)

If I change this to any number over 7200 and refresh the page, the period is still 7200.  Numbers under 7200 work as expected.

```
10:27:29.496 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 33: Configuration update received
10:27:29.497 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 33: Configuration update binding_pollperiod to 7300.0
10:27:29.497 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 33: Polling intialised at 7200 seconds - start in 7200000 milliseconds.

```

This is needed for the case of a device not checking in often (ZCOMBO) that also does not have the ability to set the wake interval.  The wake interval is long on this device to preserve battery.  

Today, with it set to 7200, this device fails to respond to polling and is marked dead.  Perhaps raise the limit to 86400 which is one day?  

I am having trouble seeing the intervals as the polling information only shows up in DEBUG, and due to the length between events, and the amount of log entries (properly so), the correlation is across very many large log files.  I am continuing to try to find the proper interval.

**Comment by cdjackson** [comment]
Done (well, in the pipeline)...
