### ISSUE TITLE
HABMIN Server is offline

### ISSUE THREAD

**Issue by RomanHAuto** [openhab/org.openhab.ui.habmin#244]
Hello,

I have two problems:

First:
I installed OH2 on Synology. It is working and I can connect to web with UI(Paper, Basic...etc). I copy habmin.jar to folder OH2 addons. But my problem is when I start UI habmin2 I got error message "The Server is offline" and I can do anything.

![image](https://cloud.githubusercontent.com/assets/23153135/19838082/bde4a712-9ec7-11e6-959e-c3c1d87f68ee.png)

Second:
How can I add Aeon USB ZWave stick to OH2 and is somewhere jar of zwave products?

Thank you for you help.

Roman
##

**Comment by cdjackson** [comment]
I’m not sure why the server would show offline - it polls the REST interface to decide this so if the REST is working, then it should work unless you’ve got some sort of strange server setup. I’d suggest another browser to see if that helps, but I suspect not.

For ZWave, please read see here or check the forum.
http://www.cd-jackson.com/index.php/openhab/habmin/10-habmin-zwave-binding-initialisation <http://www.cd-jackson.com/index.php/openhab/habmin/10-habmin-zwave-binding-initialisation>

**Comment by RomanHAuto** [comment]
I tested it in Chrome, FF and I got the same error message. As server I use Synology where I installed this file OpenHAB-2.0.0.007-SNAPSHOT-DSM6-syno-noarch-0.001.apk.  This apk I installed on Synology and then I only copied to addons habmin jar.

**Comment by cdjackson** [comment]
Sorry - I’m not sure what’s up then. I also use a synology (although not the sinology package) and it works fine. I’m not sure what else I can suggest other than using the debugger to see what is failing.

**Comment by RomanHAuto** [comment]
How can I debug it?

**Comment by cdjackson** [comment]
If you are using Chrome, open the debugger in the menu (more tools | developer tools) and then look to see what errors are shown in the console. Firefox and Safari have similar features.

**Comment by RomanHAuto** [comment]
It is the main problem  "GET http://192.168.1.3:8080/rest 503 (Jersey is not ready yet!)". 23 errors with this message. Could you help me with this problem?

**Comment by cdjackson** [comment]
If Jersey isn’t ready, then it probably means there’s something wrong with the server - I suspect it’s not related to HABmin. I would try using the REST interface from the dashboard to see what that shows.

**Comment by RomanHAuto** [comment]
Do you know what can be wrong? I only installed package  and I started OH2. Nothing wasn´t configurated. Only copy habmin to addons.
Is there some possibility to install OH2 to Synology without package?

**Comment by cdjackson** [comment]
No - I don’t know what’s wrong - sorry. It must be in the server though - not HABmin.

Yes - you can install OH into Syno using a standard install without the syno package - it’s just a normal OH2 install.
