### ISSUE TITLE
Habmin2 Installation directions for OpenHab2

### ISSUE THREAD

**Issue by joelicious** [openhab/org.openhab.ui.habmin#258]
According to the instructions here:
https://github.com/openhab/org.openhab.ui.habmin/wiki/HABmin2-installation-for-OpenHAB-2

the habmin jar should be available from either the releases folder or the working folder.  The releases folder only contains zip files (no jars) and the working folder link is not found.

The link at the top of the page states that there is updated information here: http://docs.openhab.org/addons/uis/habmin/readme.html

but there is no installation directions.

Having trouble finding the jar to install to the add ons directory.

Thanks,
joe

**Comment by cdjackson** [comment]
Habmin should be installed now in the same way as other UIs or addons - IE through paperUI or the addons config file.

**Comment by The1Percent** [comment]
Looks like this broke in OH2.1 as it installs habmin 2.0 still, and there does not appear to be a way to update it.

**Comment by boerreth** [comment]
Is there any standard way to install Habmin 2.1?
Only get 2.0 with standard installation

**Comment by cdjackson** [comment]
The version number hasn't updated, but it's the same software. The only thing that will change is the version number.

**Comment by boerreth** [comment]
Thanks Chris. But is it possible to change theme?

**Comment by cdjackson** [comment]
No - the theme is currently fixed.

**Comment by heX16** [comment]
> Habmin should be installed now in the same way as other UIs or addons - IE through paperUI or the addons config file.

http://127.0.0.1:15880/paperui/index.html#/extensions

May be correct installation guide?
