### ISSUE TITLE
GoControl (Nortek) GB00Z not initializing

### ISSUE THREAD

**Issue by mlgentry** [openhab/org.openhab.ui.habmin#260]
Hi Chris:

I have an issue with the GoControl (Nortek) GB00Z not initializing. I have included the link to the device from the Z-Wave Alliance database:

http://products.z-wavealliance.org/products/1521

I have also included the Openhab2 generated XML file (as a PDF).
 
The following is the message from PaperUI. Is there anything else you need?
Could the zwave device type be incorrect?

Thanks,
Marvin

Z-Wave Node 15 (014F:4742:3030:1.4)
Unknown Device
This device has not been fully discovered by the binding. There are a few possible reasons for this -: 
•	The device is not in the database. If the device attributes show that this device has a valid manufacturer ID, device ID and type, then this is likely the case (eg. you see a label like "Z-Wave node 1 (0082:6015:020D::2.0)"). Even if the device appears to be in the database, some manufacturers use multiple sets of references for different regions or versions, and your device references may not be in the database. In either case, the database must be updated and you should raise an issue to get this addressed. 
•	The device initialisation is not complete. Once the device is included into the network, the binding must interrogate it to find out what type of device it is. One part of this process is to get the manufacturer information required to identify the device, and until this is done, the device will remain unknown. For mains powered devices, this will occur quickly, however for battery devices the device must be woken up a number of times to allow the discovery phase to complete. This must be performed with the device close to the controller. 
________________________________________
Status: ONLINE 
hide properties
zwave_class_basic	ROUTING_SLAVE
zwave_class_generic	ALARM_SENSOR
zwave_frequent	false
zwave_neighbours	1,3
zwave_version	1.4
zwave_listening	false
zwave_deviceid	12336
zwave_nodeid	15
zwave_routing	true
zwave_wakeup_time	2017-04-02T06:10:11Z
zwave_beaming	true
zwave_class_specific	ALARM_SENSOR_ROUTING
zwave_manufacturer	335
zwave_devicetype	18242

[node15.zip](https://github.com/openhab/org.openhab.ui.habmin/files/888386/node15.zip)

**Comment by cdjackson** [comment]
This device was only added to the database yesterday, and I think the build system has been broken since it was added so this probably explains your issue.

**Comment by mlgentry** [comment]
Thanks for the quick response Chris. So do I just need to re-include the device?

**Comment by cdjackson** [comment]
You will need to update to the latest snapshot - once the builds are working again. I just checked and it’s not been building correctly for the past couple of days, so until this gets resolved the zwave binding won’t be updated either.

Once you’ve updated the binding then it should hopefully work ok - no need to re-include or anything.

**Comment by mlgentry** [comment]
Thanks Chris. Has the build completed?  Where can I download it from? If I'm understanding correctly, I would just do an uninstall in the PaperUI and copy the updated .jar in the addons directory?

Thanks,
Marvin

**Comment by cdjackson** [comment]
No - builds are still not working on the complete openhab system at the moment.

**Comment by mlgentry** [comment]
Thanks Chris. Has the build completed? It's got to working by now.

**Comment by cdjackson** [comment]
Yes.
