### ISSUE TITLE
Add Heiman Technology Co. Ltd - dx1cg-z - CH4 Sensor

### ISSUE THREAD

**Issue by MarcoFre** [openhab/org.openhab.ui.habmin#270]
Hi,
I am not able to make PR so I am following your suggestion to open issue. I have already added this CH4 gas sensor to http://www.cd-jackson.com below 2 xml files as output for openhab 1:
- product.xml
<Manufacturer>

  <Id>0260</Id>
  <Name>Heiman Technology Co. Ltd</Name>

  <Product>
    <Reference>
      <Type>8003</Type>
      <Id>1000</Id>
    </Reference>
    <Model>dx1cg-z</Model>
    <Label lang="en">CH4 Gas Sensor</Label>
    <ConfigFile>heiman/dx1cgz.xml</ConfigFile>
  </Product>

</Manufacturer> 
- product xml
<?xml version="1.0" encoding="utf-8"?>
<Product>
    <Model>dx1cg-z</Model>
    <Label lang="en">CH4 Gas Sensor</Label>

    <CommandClasses>
        <Class>
            <id>0x00</id>             
        </Class>
        <Class>
            <id>0x20</id>             
        </Class>
        <Class>
            <id>0x71</id>             
        </Class>
        <Class>
            <id>0x72</id>             
        </Class>
        <Class>
            <id>0x85</id>             
        </Class>
        <Class>
            <id>0x86</id>             
        </Class>
    </CommandClasses>

</Product>

Please add it for openhab 1 zwave binding and provide me link to download last snapshot
Thanks so much for you support
Have nice day

Marco

**Comment by cdjackson** [comment]
You can't create a PR here - this is the habmin repository for OH2, not the ZWave repository for OH1.  Please make a PR against OH1 repository.
