### ISSUE TITLE
Please add a device to the Catalog Steinel L 810 LED iHF Z-Wave

### ISSUE THREAD

**Issue by jtb0** [openhab/org.openhab.ui.habmin#272]
Hi,

I dont know, how to add this.
So, can somebody please add the following XML-File?
I got it from here: https://products.z-wavealliance.org/Products/2309/XML

Thank you very much.

[ZC10-17045557.XML.txt](https://github.com/openhab/org.openhab.ui.habmin/files/1334447/ZC10-17045557.XML.txt)

**Comment by cdjackson** [comment]
Please check cd-jackson.com for information on the database.

**Comment by jtb0** [comment]
Hi!
I already did. But this product is not in there. I read that I should open an issue and attach the xml if I don't know how to insert and do a pull request. 

So I followed the link and opened the issue. 


Am 26. September 2017 21:32:44 MESZ schrieb Chris Jackson <notifications@github.com>:
>Please check cd-jackson.com for information on the database. 
>
>Sent from my iPhone
>
>> On 26 Sep 2017, at 19:34, jtb0 <notifications@github.com> wrote:
>> 
>> Hi,
>> 
>> I dont know, how to add this.
>> So, can somebody please add the following XML-File?
>> I got it from here:
>https://products.z-wavealliance.org/Products/2309/XML
>> 
>> Thank you very much.
>> 
>> ZC10-17045557.XML.txt
>> 
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/org.openhab.ui.habmin/issues/272#issuecomment-332310340

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by cdjackson** [comment]
I think the instructions on the database say to register so you can add the device.

**Comment by jtb0** [comment]
Ok, I tried.
I register and logged in, but there is no 'add' button like you shown in the screen shots.
Maybe there is sth. wrong with my login? 

I tried with FF and chrome.
Both times same behaviour. There is no green add button.

What can I do?

Thanks

**Comment by cdjackson** [comment]
In the instructions (in bold) it states you need to email so that I can give you access to edit. Please provide your username and I can update your access.

**Comment by jtb0** [comment]
Oh, right...
sorry, it was too late yesterday.
