### ISSUE TITLE
Install instructions - openhab2 ?

### ISSUE THREAD

**Issue by Netoperz** [openhab/org.openhab.ui.habmin#275]
Hello, i'm sorry if the question is kind of "stupid" but where can i find info about how to install that addon ?

I was looking here and there and just can't find any tutorial or step by step info on how to install HABmin on clean openhab2..

Could someone throw me a bone in this matter ?

thx.

**Comment by cdjackson** [comment]
It’s the same as any other OH addon. Use PaperUI - simply find HABmin in the list of addons, and click install.

**Comment by Netoperz** [comment]
Fine, but when i start paperui and i'm going to add ons on the left menu, i see bindings misc voice, and there is no habmin on those lists, so i think that i should do something more.

The OH was installed manually, just downloaded,  and started in tmux session, so  maby i should download package and put that in to the addons folder or what ?

:)

**Comment by cdjackson** [comment]
Please discuss this sort of issue on the community forum. Thanks.

**Comment by Netoperz** [comment]
`binding="hue,yahooweather,zoneminder,samsungtv,lgtvserial,chromecast,airquality,ipp,milight,ntp,opensprinkler,rfxcom,rme,sonos,wifiled,zwave,zigbee,zway"
felix.fileinstall.filename="file:/home/stellarlock/Hab/openhab/userdata/etc/org.openhab.addons.cfg"
misc="ruleengine,openhabcloud"
package="simple"
remote="true"
service.pid="org.openhab.addons"
ui="paper,habpanel"`

that is the content of userdata/config/org/openhab/addons.config

that's why i can't se the habmin there.

Thanks, I will ask somewhere else than.

Cheers.

P.S. The doc's are not very good for someone that starts from OH 2, because most of them is reffering to the OH 1.x and there was so many changes in 2.0 that some advices are not relevant.
