### ISSUE TITLE
Habmin displays associations incorrectly

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/org.openhab.ui.habmin#279]
OH 2.3.0 snapshot 1159
Zwave 2.2.0.201801021718 

Depending on the type of device, associations display as empty or a blank with an X...
![image](https://user-images.githubusercontent.com/21967853/34493725-3e1e3e94-efbb-11e7-8492-3be909b5925c.png)

![image](https://user-images.githubusercontent.com/21967853/34493699-1a46b1fe-efbb-11e7-92d9-aac24be97c06.png)

PaperUI displays them correctly for me. I see this with the dev version of the binding, but IIRC, others have reported this with the 2.3 release version too.

**Comment by meyercg** [comment]
Same here. I have a device with association groups problem as well. But only one up to now.

**Comment by lsiepel** [comment]
https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653/3003

**Comment by cdjackson** [comment]
As said elsewhere, this issue seems to be related to the widget used to display the list, which seems to be no longer maintained so it's a major issue to fix this unfortunately.

If anyone has any ideas for good dropdown/select widgets, please feel free to suggest.
