### ISSUE TITLE
Show disabled state of z-wave things

### ISSUE THREAD

**Issue by tolotos-rgu** [openhab/org.openhab.ui.habmin#307]
The network viewer shows disabled z-wave things still as present. 
The device should be painted grayish and the neightbor lines should be painted separately as well. 
I suggest the following line styles:

<disabled thing> =(to)=> <active thing> := doted line in gray (only visible if device is selected)
<active thing> =(to)=> <disabled thing> =: doted line in red (always visible)
 

[https://community.openhab.org/t/disable-z-wave-things/63466](https://community.openhab.org/t/disable-z-wave-things/63466)

**Comment by cdjackson** [comment]
> On 12 Jan 2019, at 13:09, Rüdiger Gubler <notifications@github.com> wrote:
> 
> The network viewer shows disabled z-wave things still as present.
> 
> 

The network viewer shows the ZWave network. There is no such thing as “disabled” in the network, so I’m not really sure what this is getting at? Please can you explain the meaning of a disabled node?

**Comment by tolotos-rgu** [comment]
I have a outdor switch for the christmas lights. This thing is only plugedin a few weeks every year. The remaining time the device is disabled in OH and stored in a box together with the lights. 
Therefor for me a disabled thing is no longer a part of the network. It disabled to avoid error message from OH as the thing is not reachable.

**Comment by cdjackson** [comment]
We are having the same conversation in multiple places, so I will close this here and we can continue on the forum as I've already answered there.
